config/routes.rb
Rails.application.routes.draw do
  get 'homes/show'
resources :homes, only: [:show]

  resources :stories do
      member { post :vote }
  end

    
 devise_for :users,  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :phases

  resources :folders

  get 'users/dashboard'
  get 'charges/index'
  get 'charges/create'
  get 'users/home'
  get 'users/myphase'
  get 'users/mystories'

  
  
  root :to => "users#dashboard"

resources :charges

end

app/models/folder.rb
class Folder < ActiveRecord::Base
	belongs_to :user 
	has_many :phases, dependent: :destroy

	attr_accessible :name , :user_id

	validates :name, :presence => true,
			  :length => { :within => 1..10 }
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]
   before_filter :login_required, only: [:show, :new, :edit, :update, :destroy]
  # GET /folders
  # GET /folders.json
  def index
     
   @folders =  Folder.where(user_id: "#{current_user.id}")
    @fol = @folders.count
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @folder = Folder.find(params[:id])
    @fol = @folder.phases
    @count = @fol.count
    @phase = Phase.new
     @phases =  Phase.where(folder_id: @folder)
  end

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  # GET /folders/1/edit
  def edit
     @folders =  Folder.where(user_id: "#{current_user.id}")
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(folder_params)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to folders_path, notice: 'Folder was successfully created.' }
        format.json { render :index, status: :created, location: @folder }
      else
        format.html { render :new }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folders_url, notice: 'Folder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit(:name , :user_id)
    end
    private
    def login_required
    unless current_user
      flash[:error] = 'You must be logged in to view this page.'
      redirect_to new_user_session_path
    end
  end

end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= form_for @folder, :html => { :class => "form-horizontal folder" } do |f| %>

    <% if @folder.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @folder.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<center>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name , :class => 'form-control' %>
      <%= f.hidden_field :user_id , :value => "#{current_user.id}" %>
    </div>
    <%= error_span(@folder[:name]) %>
  </div>

<% @folders.each do |h| %>
  
     
       <% if h.id == @folder.id %>
 <%= f.submit "Create Life", :class => 'btn btn-primary' %>
  
<% end %>
<% end %>
 
  
</center>
<% end %>

app/views/folders/_morestories.html.erb
<div class="container">
    <div class="row">
		<div class="col-md-12">
                <div id="Carousel" class="carousel slide">
                 
                <ol class="carousel-indicators">
                    <li data-target="#Carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#Carousel" data-slide-to="1"></li>
                    <li data-target="#Carousel" data-slide-to="2"></li>
                </ol>
                 
                <!-- Carousel items -->
                <div class="carousel-inner">
                    
                <div class="item active">
                	<div class="row">
                	 <div class="col-md-2">
     
                                             <div class="offer offer-warning">
          <div class="shape">
            <div class="shape-text">
              Story              
            </div>
          </div>
        
          <div class="offer-content">
            <h3 class="lead">
              <%= s.heading.truncate(6) %>
            </h3>
            <p>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_story_path(s), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                story_path(s),:method => :delete,:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
            </p>
          </div>
                                            </div>
                    </div>
                </div><!--.item-->
                 
               
                 
                </div><!--.carousel-inner-->
                  <a data-slide="prev" href="#Carousel" class="left carousel-control">‹</a>
                  <a data-slide="next" href="#Carousel" class="right carousel-control">›</a>
                </div><!--.Carousel-->
                 
		</div>
	</div>
</div><!--.container-->

app/views/folders/edit.html.erb
<%- model_class = Folder -%>
<div class="page-header">
  <h1>Edit Name of you life</h1>
</div>
<%= render :partial => 'form' %>

app/views/folders/index.html.erb
<%- model_class = Folder -%>
<div class="page-header">
  <h1> My Life</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
    <% if @folders.empty? %>
        <div class="offer offer-info">
          <div class="shape">
            <div class="shape-text">
              Life               
            </div>
          </div>
        
          <div class="offer-content">
            <h3 class="lead">
              <%= link_to "Give a name to your life" , new_folder_path %>
            </h3>
            <p>
             
            </p>
          </div>
        </div>
       <% else %>
      <% @folders.each do |f| %>
      
        <div class="offer offer-info">
          <div class="shape">
            <div class="shape-text">
              Life               
            </div>
          </div>
        
          <div class="offer-content">
            <h3 class="lead">
              <%= link_to f.name, folder_path(f)  %>
            </h3>
            <p>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_folder_path(f), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                folder_path(f),:method => :delete,:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
            </p>
          </div>
        </div>
       
    </div>
     <% end %>
     <% end %>
  </div>
  <% @folders.each do |f| %>
  <%if f.phases.empty? %>
      <div class="row">
      <div class="col-md-4">
     
        <div class="offer offer-success">
          <div class="shape">
            <div class="shape-text">
              Phase              
            </div>
          </div>
        
          <div class="offer-content">
            <h3 class="lead">
              <%= link_to "Give a name to your phase" , folder_path(f) %>
            </h3>
            <p>
             
            </p>
          </div>
        </div>
    </div>
</div>
  <% else %>
   <% f.phases.each do |p| %>
  <div class="row">
    <div class="col-md-4">
     
        <div class="offer offer-success">
          <div class="shape">
            <div class="shape-text">
              Phase              
            </div>
          </div>
        
          <div class="offer-content">
            <h3 class="lead">
              <%= link_to p.name , phase_path(p) %>
            </h3>
            <p>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_phase_path(p), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                phase_path(p),:method => :delete,:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
            </p>
          </div>
        </div>
    </div>
   <div class="col-md-1">
     <h1>
       <span class="glyphicon glyphicon-search"></span>
     </h1>
   </div>
   <% if p.stories.empty? %>
   <div class="col-md-2">
     
        <div class="offer offer-warning">
          <div class="shape">
            <div class="shape-text">
              Story              
            </div>
          </div>
        
          <div class="offer-content">
            <h3 class="lead">
              <%= link_to "Write your story.." , phase_path(p) %>
            </h3>
            <p>
             
            </p>
          </div>
        </div>
    </div>
   <% else %>

    <% p.stories.each do |s| %>

    <div class="col-md-2">
     
        <div class="offer offer-warning">
          <div class="shape">
            <div class="shape-text">
              Story              
            </div>
          </div>
        
          <div class="offer-content">
            <h3 class="lead">
              <%= s.heading.truncate(6) %>
            </h3>
            <p>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_story_path(s), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                story_path(s),:method => :delete,:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
            </p>
          </div>
        </div>
    </div>
<% end %>
<% if p.stories.count < 9 %>
      <div class="col-md-2">
     
        <div class="offer offer-warning">
          <div class="shape">
            <div class="shape-text">
              Story             
            </div>
          </div>
        
          <div class="offer-content">
            <h3 class="lead">
               <%= link_to "Write another story.." , phase_path(p) %>
            </h3>
            <p>
             
            </p>
          </div>
        </div>
    </div>

 <% end %>
<% end %>

  </div>
 <% end %>
 <% if f.phases.count < 10 %>
<div class="row">
      <div class="col-md-4">
     
        <div class="offer offer-success">
          <div class="shape">
            <div class="shape-text">
              Phase              
            </div>
          </div>
        
          <div class="offer-content">
            <h3 class="lead">
              <%= link_to "Give a name to your phase" , folder_path(f) %>
            </h3>
            <p>
             
            </p>
          </div>
        </div>
    </div>
</div>

 <% end %>

  <% end %>

<% end %>

</div>

app/views/folders/new.html.erb
<%- model_class = Folder -%>
<div class="page-header">
  <h1>My Life</h1>
</div>
<%= render :partial => 'form' %>

app/views/folders/show.html.erb
<%- model_class = Folder -%>
<div class="page-header">
<center><h3><%=t '.title', :default => @folder.name.titleize %></h3></center>
 
     <p>  
      <% if can? :update, @folder %>  
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_folder_path(@folder), :class => 'btn btn-default' %>
      <% end %>  
      <% if can? :destroy, @folder%>  
         <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              folder_path(@folder),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
      <% end %>  
    </p>  
 
 
</div>

<% if @count >= 10 %>
   <div class="container">
      <div class="row">

 <% @phases.each do |phase| %>


<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <div class="offer offer-info">
        <div class="shape">
          <div class="shape-text">
            Phase              
          </div>
        </div>
        <div class="offer-content">

        <%= link_to phase.name , phase_path(phase)  %>
          <h3 class="lead">
           
          </h3>
          <p>
           
          </p>
        </div>
      </div>
    </div>
 


    
       
  






 <% end %>
</div>
</div>


 <h1> <%= link_to "Donate" , new_charge_path ,:method => :get %> to add more phases </h1>
 <%else %>
 
<h1> you have <%= @count %> phases out of 3</h1>

 <div class="container">
  <div class="row">

 <% @phases.each do |phase| %>



 

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <div class="offer offer-info">
        <div class="shape">
          <div class="shape-text">
            Phase              
          </div>
        </div>
        <div class="offer-content">

        
          <h3 class="lead">
           
          </h3>
          <p>
           <%= link_to phase.name , phase_path(phase)  %>
          </p>
        </div>
      </div>
    </div>
 <% end %>



<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <div class="offer offer-info">
        <div class="shape">
          <div class="shape-text">
            Phase              
          </div>
        </div>
        <div class="offer-content">

        
          <h3 class="lead">
           
          </h3>
          <p>
            <button class="btn btn-primary" data-toggle="modal" data-target="#myModal">
              Add phase
            </button> 
          </p>
        </div>
      </div>
    </div>
    </div>

 <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"> Create New phase</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@phase) do |f| %>
  <% if @phase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phase.errors.count, "error") %> prohibited this phase from being saved:</h2>

      <ul>
      <% @phase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <%= f.hidden_field :folder_id , :value => "#{@folder.id}" %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       
      </div>
    </div>
  </div>
</div>

</div>






<% end %>