config/routes.rb
Rails.application.routes.draw do
  get 'homes/show'
resources :homes, only: [:show]

  resources :stories do
      member { post :vote }
  end

    
 devise_for :users,  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :phases

  resources :folders

  get 'users/dashboard'
  get 'charges/index'
  get 'charges/create'
  get 'users/home'
  get 'users/myphase'
  get 'users/mystories'

  
  
  root :to => "users#dashboard"

resources :charges

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_create :set_default_roles
 
   acts_as_voter
  has_reputation :votes, source: {reputation: :votes, of: :stories}, aggregated_by: :sum
  
  has_many :folders
  has_many :phases, through: :folders
  has_many :stories, through: :phases
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,:confirmable, :lockable, :timeoutable, :omniauthable  ,:omniauth_providers => [:facebook]

         attr_accessible :email, :password, :password_confirmation

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
user = User.where(:provider => auth.provider, :uid => auth.uid).first
if user
return user
else
registered_user = User.where(:email => auth.info.email).first
if registered_user
return registered_user
else
user = User.create(#name:auth.extra.raw_info.name,
provider:auth.provider,
uid:auth.uid,
email:auth.info.email,
password:Devise.friendly_token[0,20],
)
end end
end


def voted_for?(story)
  evaluations.where(target_type: story.class, target_id: story.id).present?
end


 private
    def set_default_roles
      self.roles = ['Default']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @folders = Folder.all
    @phase = Phase.all
    @stories = Story.all
  	
  end
  def home
  	 @stories = Story.order('created_at desc').page(params[:page])
 
 
  end
  def myphase
  	@folders =  Folder.where(user_id: "#{current_user.id}")
  	
  end
  def mystories
  	@folders =  Folder.where(user_id: "#{current_user.id}")
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<link href='http://fonts.googleapis.com/css?family=Buenard:700' rel='stylesheet' type='text/css'>
<script src="http://pupunzi.com/mb.components/mb.YTPlayer/demo/inc/jquery.mb.YTPlayer.js"></script>

<!--Video Section-->
<section class="content-section video-section">
  <div class="pattern-overlay">
  <a id="bgndVideo" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=fdJc1_IBKJA',containment:'.video-section', quality:'large', autoPlay:true, mute:true, opacity:1}">bg</a>
    <div class="container">
      <div class="row">
       <div class="col-md-12 text-center">
                    <h3>
                        Share your private life "BEING UNKNOWN"</h3>
                    <h3>
                        Tell us about every thing happend to you..and read about others
                    </h3>
                    <div class="">
                   <% if user_signed_in? %>
                   <h3>Wellcome <%= current_user.email %></h3>
                   <p>
                    <h3> Tell use about your <%= link_to "Life" , folders_path %> or  <%= link_to "Read", users_home_path %> about others...</h3>
                   </p>
                   <% else %>
                    <%= link_to "Login" , new_user_session_path , :class => "btn btn-info btn-sm btn-min-block" %>
                         <%= link_to "Register" , new_user_registration_path, :class => "btn btn-warning btn-sm btn-min-block" %>
                       <% end %>
                        </div>
                
                        
                </div>
      </div>
    </div>
  </div>
</section>

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    <p id ="about" > </p>
 <hr class="featurette-divider">
    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
         
      
     
    <div class="row">
    <div class="btn-group btn-group-justified">
            <div class="btn-group">
                <button type="button" class="btn btn-nav active">
                    
              <h3><%= @folders.count %> Lifes..</h3>
                </button>
            </div>
            <div class="btn-group">
                <button type="button" class="btn btn-nav active">

              <h3><%= @phase.count %> phases..</h3>
                </button>
            </div>
            <div class="btn-group">
                <button type="button" class="btn btn-nav active">
                   
              <h3><%= @stories.count %> stories..</h3>
                </button>
            </div>
           
        </div>
  </div>
</div><!-- End row -->
      
      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->
<div class="container">
  <div class="row">
        <!-- Boxes de Acoes -->
      <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="box">             
        <div class="icon">
          <div class="image"><i class="fa fa-thumbs-o-up"></i></div>
          <div class="info">
            <h3 class="title">Marilyn Monroe</h3>
            <p>
              “<b>This life</b> is what you make it. No matter what, you're going to mess up sometimes, But the good part is you get to decide how you're going to mess it up.All'll act like it anyway. But just remember, some come, some go"
            </p>
            
          </div>
        </div>
        <div class="space"></div>
      </div> 
    </div>
      
        <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="box">             
        <div class="icon">
          <div class="image"><i class="fa fa-flag"></i></div>
          <div class="info">
            <h3 class="title">Charlin Chaplin</h3>
              <p> 
             "<b>Phases of Life</b> is a puzzle. Sometimes it makes us laugh. Sometimes it makes us cry." We deal with different events and stages in life different ways. Understand and appreciate life by reading these life quotes.
            </p>
            
          </div>
        </div>
        <div class="space"></div>
      </div> 
    </div>
      
        <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="box">             
        <div class="icon">
          <div class="image"><i class="fa fa-desktop"></i></div>
          <div class="info">
            <h3 class="title">Rabindranath Tagor</h3>
              <p>
              We need to know ourselves... to understand others better.
            </p>
           
          </div>
        </div>
        <div class="space"></div>
      </div> 
    </div> 
    <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="box">             
        <div class="icon">
          <div class="image"><i class="fa fa-desktop"></i></div>
          <div class="info">
            <h3 class="title">Ralph Waldo Emerson</h3>
              <p>
             It is one of the beautiful compensations of life that no man can sincerely try to help another without helping himself.
            </p>
           <div class="more">
           <%= link_to "Donate >>" , new_charge_path , method: :get %>
               
              
            </div>
          </div>

        </div>
        <div class="space"></div>
      </div> 
    </div>             
    <!-- /Boxes de Acoes -->
  </div>
</div>

      <!-- FOOTER -->
    


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    

app/views/users/home.html.erb
<%- model_class = Story -%>
<div class="page-header">
  <h1><%=t '.title', :default => "New Stories" %></h1>
</div>

  <div class="container">
  <% @stories.each do|s| %>
  <m id = "posts"> 
   <n class = "page">
    <% if s.created_at.strftime("%Y%m%d")  >= Time.now.strftime("%Y%m%d")  %>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="offer offer-success">
            <div class="shape">
              <div class="shape-text">
                New               
              </div>
            </div>
          
            <div class="offer-content">
              <h3 class="lead">
                <%= s.heading %>
              </h3>
              <p>
                  <%= s.describtion.truncate(75) %><%= link_to "Read more..", story_path(s)  %> 
              </p>
     <% elsif s.updated_at.strftime("%Y%m%d")  >= Time.now.strftime("%Y%m%d")  %>
               <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                 <div class="offer offer-primary">
                    <div class="shape">
                      <div class="shape-text">
                        Edit               
                      </div>
                    </div>
                
                  <div class="offer-content">
                    <h3 class="lead">
                      <%= s.heading %>
                    </h3>
                    <p>
                      <%= s.describtion.truncate(75) %><%= link_to "Read more..", story_path(s)  %> 
                    </p>
      <% else %>
          <div class="col-md-3">
            <div class="offer offer-default">
              <div class="shape">
                <div class="shape-text">
                  old             
                </div>
              </div>
            
            <div class="offer-content">
              <h3 class="lead">
                <%= s.heading.truncate(15) %>
              </h3>
              <p>
                  <%= s.describtion.truncate(20) %><%= link_to "Read more..", story_path(s)  %> 
              </p>
      <% end %>     
      
      </div>
      </div>
      </div>

     <% end %>
    </n>
  </m>
      </div>
      </div>
      </div>
     <center>
         <%= paginate @stories%>

      </center>
       
<!-- Modal -->

app/views/users/index.js.erb
$("#posts").append("<n class='page'><%= escape_javascript(render(@stories)) %></n>");

app/views/users/myphase.html.erb
<% @folders.each do |p| %>
 <% p.phases.each do |phase| %>
 	<%= phase.name %>
 <% end %>
<% end %>

app/views/users/mystories.html.erb
<div class = "container">
<div class = "row"> 
<% @folders.each do |f| %>
  <% f.phases.each do |p| %>
    <% p.stories.each do |s| %>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="offer offer-default">
        <div class="shape">
          <div class="shape-text">
            Story               
          </div>
        </div>
        <div class="offer-content">
          <h3 class="lead">
           <%= s.heading %>
          </h3>
          <p>
            <%= s.describtion.truncate(18) %>
                   <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_story_path(s), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      story_path(s),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          </p>
        </div>
      </div>
    </div>
      

    <% end %>
  <% end %>

<% end %> 
</div>di
</div>