config/routes.rb
Rails.application.routes.draw do
  get 'homes/show'
resources :homes, only: [:show]

  resources :stories do
      member { post :vote }
  end

    
 devise_for :users,  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :phases

  resources :folders

  get 'users/dashboard'
  get 'charges/index'
  get 'charges/create'
  get 'users/home'
  get 'users/myphase'
  get 'users/mystories'

  
  
  root :to => "users#dashboard"

resources :charges

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PandSoft </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>



<div class="navbar-wrapper">
  

        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to "PandSoft Inc" , users_dashboard_path , method: :get, :class => "navbar-brand" %>
            
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                
                <% if signed_in? %>
                <li><%= link_to "Stories" , users_home_path %></li>
                <li><%= link_to "My Life" , folders_path %></li>
               
                <li><%= link_to "Contribute" , new_charge_path , :method => :get %></li>
                <% end %>
                
                

              </ul>
               <ul class="nav navbar-nav navbar-right">
                <% if signed_in? %>

                <li><%= link_to "signout" ,destroy_user_session_path , :method=>:delete , :class => "btn btn-default"%></li>
                <% else %>
                <li><%= link_to "Sign Up" , new_user_registration_path , :class => "btn btn-default" %></li>
                <li><%= link_to "Sign In" , new_user_session_path , :class => "btn btn-default"%></li>
                <% end %>
                  
                </ul>
            </div>
          </div>
      

      </div>

<% flash.each do |type, message| %>
       <div class=" alert alert-<%= bootstrap_class_for(type) %>">
        <button class="close" data-dismiss="alert">×</button>
        <%= message %>
        </div>
<% end %>
<%= yield %>
<hr>
<div class = "container">
<footer>
        <p class="pull-right"><a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left"><span class="fa fa-chevron-up"></span></a>
      </p>
<table>
  <tr>
    
    <td>
      &copy; 2014 PandSoft, Inc. &middot;
    </td>
    <td>
      <a href="//www.iubenda.com/privacy-policy/998700" class="iubenda-white iubenda-embed" title="Privacy Policy">Privacy Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src = "//cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>
    </td>
    <td>
       <script class = "pull-right">
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1444699415786014',
      xfbml      : true,
      version    : 'v2.1'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
  <f
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</f>
    </td>
  </tr>

</table>
</footer>
    
</div>


</body>
</html>